### ISSUE TITLE
App didnt work after killed (or removing from recent app mode) for a few minutes 

### ISSUE THREAD

**Issue by yassermohammad** [transistorsoft/flutter_background_geolocation#675] opened 2021-11-28 14:41 UTC
## Your Environment
* Plugin version: 4.3.2
* Platform: Android
* OS version: 10
* Device manufacturer / model: Nokia C3
* Flutter info (`flutter doctor`): all OK
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.onLocation((bg.Location location) {
        _content = encoder.convert(location.toMap());

        Map coords = {
          'lat' : _lat = location.coords.latitude,
          'lng' : _lng = location.coords.longitude,
          'mode' : AppLifecycleState.resumed == _notification ? 'resumed' : 'other'
        };
        dio().post('/location', options: Dio.Options(headers: {'Authorization' : 'Bearer 6|FtuHsDLtDjiFh4hOmIJoRPMtV49JPknqBPvTYD9w'}), data: coords).then((response) {
          if (response.statusCode == 200) {
            if (AppLifecycleState.resumed == _notification) {
              if (mounted) {
                setState(() {
                  _advs = (response.data as List).map((val) => DlAdvertise.fromJson(val)).toList();
                });
              }
            } else {
              if ((response.data as List).isNotEmpty) {
                notification.showNotificationCustomSound();
              }
            }
          }
        });
      });

      bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
        print('[motionchange] - $location');
      });

      // Fired whenever the state of location-services changes.  Always fired at boot
      bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
        print('[providerchange] - $event');
      });

      bg.BackgroundGeolocation.ready(
          bg.Config(
            locationAuthorizationRequest: "Always",
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            enableHeadless: true,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            reset: false,
            autoSync: false,
            foregroundService: true,
          )
      ).then((bg.State state) {
        if (!state.enabled) {
          bg.BackgroundGeolocation.startSchedule();
        }
      });
```

## Expected Behavior

first: it should work after kill the app (remove from recent app)
second: it has to post request to server to log the location

## Actual Behavior

first: tracking location does not work after killing the app and it maybe work after a few minutes or 2 or 3 km
second: does not send data to server

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment] 2021-11-28 18:10
See http://dontkillmyapp.com.

The Nokia device that I test on performs poorly, taking a longer than normal distance to initiate tracking.

**Comment by yassermohammad** [comment] 2021-11-29 09:28
It still does not work...

**Comment by christocracy** [comment] 2021-11-29 10:33
> reset: false,

Why are you doing this?  Do you know what it does?  99,9% of developers do not need that.

Delete that option or set it to `true`.

See wiki *Debugging*.

**Comment by Theunodb** [comment] 2022-01-10 09:37
I'm experiencing the same issue on iOS, on a real device and simulator. I'm commenting on this issue because i can consistently reproduce it. Please have a look to see why i am doing wrong

This is what i do to reproduce it:

1. Stop the debugging / project in IDE, make sure nothing is running.
2. Force close the app by swiping from bottom and closing. Make sure the app isnt running in the background.
3. Set simulator location by going to features -> Location -> City run
4. Confirm the location is updating by opening up the native maps app, close all running apps on the simulator
5. Start the app in debugging mode by running it through the IDE
6. See the last location loading fine, but no further location updates (2022-01-10 11:32:21)
7. After +- 90 seconds the location starts to update (2022-01-10 11:33:40)
8. After that location tracking works as expected (Updating ui and updating the document on firebase)

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           34,8s
Debug service listening on ws://127.0.0.1:62027/Yl0fqBCnlZU=/ws
Syncing files to device iPhone 13...
flutter: LocationPermissionCubit - Permission granted AUTHORIZATION_STATUS_ALWAYS |
flutter: LocationTrackerCubit - Initialising tracker - 2022-01-10 11:32:21.703407 |
flutter: LocationTrackerCubit - Getting last known location |
flutter: LocationTrackerCubit - Last location loaded - 2022-01-10 11:32:21.722060 |
flutter: LocationTrackerCubit - LocationTracker platform initialised completed - 2022-01-10 11:32:21.758973 |
flutter: LocationTrackerCubit - Starting Location Tracking |
flutter: LocationTrackerCubit - Getting GeoFenceListeners |
flutter: LocationTrackerCubit - Location Tracker GeoFences Loaded |
Document successfully written
Google Maps SDK for iOS version: 6.0.1.0
flutter: LocationTrackerCubit - Location received - 2022-01-10 11:33:40.580463 |
flutter: LocationTrackerCubit - Location received - 2022-01-10 11:33:40.599084 |
Document successfully written
flutter: LocationTrackerCubit - Location received - 2022-01-10 11:33:43.527662 |
Document successfully written
flutter: LocationTrackerCubit - Location received - 2022-01-10 11:33:46.549784 |
Document successfully written
Application finished.
```

I'm using cubits, and i call initPlatformState on startup
```
  initPlatformState({
    required String locationPath,
    required String geoFencesPath,
    required String permissionRationaleMessage,
    int activityType = Config.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
    int desiredAccuracy = Config.DESIRED_ACCURACY_HIGH,
    double desiredOdometerAccuracy = 100,
    double distanceFilter = 5,
    bool updateSingleDocument = true,
  }) async {
    emit(LocationTrackerLoading(state.mainLocationTrackerState.copyWith(message: 'Initialising tracker - ${DateTime.now()}', errorMessage: '')));

    getLastKnownLocation();

    try {
      await BackgroundGeolocationFirebase.configure(
        BackgroundGeolocationFirebaseConfig(
          locationsCollection: "$locationPath",
          geofencesCollection: "$geoFencesPath",
          updateSingleDocument: updateSingleDocument,
        ),
      );

      await BackgroundGeolocation.ready(
        Config(
          logLevel: Config.LOG_LEVEL_DEBUG,
          geofenceInitialTriggerEntry: true,
          activityType: activityType,
          desiredAccuracy: desiredAccuracy,
          desiredOdometerAccuracy: desiredOdometerAccuracy,
          distanceFilter: distanceFilter,
          backgroundPermissionRationale: PermissionRationale(
            title: "Allow access to this device's location in the background?",
            message: permissionRationaleMessage,
            positiveAction: "Change to Allow all the time",
            negativeAction: "Cancel",
          ),
        ),
      );

      BackgroundGeolocation.onLocation((Location location) {
        emit(LocationTrackerDetailLoaded(state.mainLocationTrackerState.copyWith(location: location, message: 'Location received - ${DateTime.now()}')));
      });

      BackgroundGeolocation.onGeofence((GeofenceEvent geofenceEvent) {
        emit(GeofenceEventTriggered(state.mainLocationTrackerState.copyWith(
          action: geofenceEvent.action,
          location: geofenceEvent.location,
          identifier: geofenceEvent.identifier,
          extras: geofenceEvent.extras,
          message: 'GeofenceEventTriggered',
          errorMessage: '',
        )));
      });

      emit(LocationTrackerPlatformInitialised(state.mainLocationTrackerState.copyWith(message: 'LocationTracker platform initialised completed - ${DateTime.now()}', errorMessage: '')));
    } catch (error) {
      emit(LocationTrackerError(state.mainLocationTrackerState.copyWith(message: '', errorMessage: error.toString())));
    }
  }
```

I use the values thats being emitted by BackgroundGeolocation.onLocation to update my UI

**Comment by christocracy** [comment] 2022-01-10 14:48
>Force close the app by swiping from bottom and closing. Make sure the app isnt running in the background.

See API docs `Config.stopOnTerminate (default true)`.

**Comment by christocracy** [comment] 2022-01-10 17:52
See api docs .changePace

**Comment by Theunodb** [comment] 2022-01-11 06:16
I can confirm this is working 100%  after i called changePage

Thank you for the awesome package, and the great support!

**Closed** 2022-01-11 10:21 UTC
