### ISSUE TITLE
Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent

### ISSUE THREAD

**Issue by racacere** [transistorsoft/flutter_background_geolocation#96] opened 2019-07-18 05:23 UTC
## Your Environment
* Plugin version: 1.0.11
* Platform: Android
* OS version: 9
* Device manufacturer / model: moto g6
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CL) 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        foregroundService: true,
        startOnBoot: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true,
        debug: true,
        enableHeadless: true,
        disableElasticity: true
    )).then((bg.State state) {
      if (!state.enabled) bg.BackgroundGeolocation.start();
    });
```

## Expected Behavior
The app must track the device location 24/7 even if the app is terminated

## Actual Behavior
When the app is terminated, geolocation successfully start again, but when a headless event is fired up, appears this error in the logs: 
```
2019-07-18 00:04:13.758 28424-28424/com.myapp.bundle E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
```

## Steps to Reproduce

1. I followed the android configuration steps of the docs included the headless steps.
2. My Application.java
```java
package com.myapp.bundle;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application  extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
    BackgroundFetchPlugin.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

3. The relevant part of my main.dart
```dart
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;

void headlessTask(bg.HeadlessEvent headlessEvent) async {
  print('\nEVENT IN BACKGROUND: $headlessEvent\n');

  switch(headlessEvent.name) {
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;  
      print('\n LOCATION CHANGE: $location\n');
      break;
    case bg.Event.PROVIDERCHANGE :
      bg.ProviderChangeEvent event = headlessEvent.event;
      print('\n PROVIDERCHANGE CHANGE: $event\n');
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print('\n MOTIONCHANGE CHANGE: $location\n');
      break;
  }
}

void main() {
  Provider.debugCheckInvalidValueType = null;
  runApp(MyApp());
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
} 

class MyApp extends StatelessWidget {
...
```

## Context
I trying to tracking the device location even if the app has been closed (terminated). As a first approach, i have configured a headless task that prints some info when an event occurs (the further plan is to replace this prints for logic that sends the device location to firebase), but when i close the app and one of the events is fired up, an error appears in the logs and the logic of the task is never executed.

This only occurs with the headless task, in any other scenario (background, foreground) the plugin works very well and sends the device location info to firebase with no problems.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
    ╔═════════════════════════════════════════════
    ║ 📶  Connectivity change: connected? true
    ╠═════════════════════════════════════════════
2019-07-18 00:04:13.447 28424-28424/com.myapp.bundle I/TSLocationManager: [c.t.l.a.BackgroundGeolocation e] 
      🎾  Start monitoring location-provider changes
2019-07-18 00:04:13.461 28424-28424/com.myapp.bundle D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
2019-07-18 00:04:13.477 28424-28424/com.myapp.bundle D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
2019-07-18 00:04:13.492 28424-28424/com.myapp.bundle D/TSLocationManager: [c.t.f.b.HeadlessTask onHeadlessEvent] 💀 [HeadlessTask providerchange]
2019-07-18 00:04:13.758 28424-28424/com.myapp.bundle E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
        at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:44)
        at com.myapp.bundle.Application.registerWith(Application.java:20)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.initFlutterView(HeadlessTask.java:189)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.onHeadlessEvent(HeadlessTask.java:107)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.e(Unknown Source:66)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:295)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:15)
        at com.transistorsoft.locationmanager.scheduler.ScheduleEvent.onOneShot(Unknown Source:30)
        at com.transistorsoft.locationmanager.scheduler.ScheduleJobService.onStartJob(Unknown Source:38)
        at android.app.job.JobService$1.onStartJob(JobService.java:62)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:215)
        at android.app.ActivityThread.main(ActivityThread.java:6939)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
2019-07-18 00:04:13.759 28424-28424/com.myapp.bundle D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent
2019-07-18 00:04:13.792 28424-28424/com.myapp.bundle D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
2019-07-18 00:04:13.809 28424-28424/com.myapp.bundle D/TSLocationManager: [c.t.f.b.HeadlessTask onHeadlessEvent] 💀 [HeadlessTask terminate]
```

</details>

**Comment by christocracy** [comment] 2019-07-23 20:54
Your issue is caused by another plugin which is not taking into account that it might be executed in the headless context.

```
at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
```

The problem is [that plugin is not checking if `registrar.activity() != null`](https://github.com/adee42/flutter_keyboard_visibility/blob/master/android/src/main/java/com/github/adee42/keyboardvisibility/KeyboardVisibilityPlugin.java#L107) (which it will be in the headless context, since there is no Android activity in that state).

That plugin needs to do this:
```diff
public static void registerWith(Registrar registrar) {
    final EventChannel eventChannel = new EventChannel(registrar.messenger(), STREAM_CHANNEL_NAME);
    KeyboardVisibilityPlugin instance = new KeyboardVisibilityPlugin(registrar);
    eventChannel.setStreamHandler(instance);

+    if (registrar.activity() != null) {   // <-- ensure activity exists.
+    	registrar.activity().getApplication().registerActivityLifecycleCallbacks(instance);
+    }
    
}

```

**Closed** 2019-07-23 20:54 UTC
