### ISSUE TITLE
[BUG] Crash when calling bgGeo.BackgroundGeolocation.stop(). java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient'

### ISSUE THREAD

**Issue by emaddoma** [transistorsoft/flutter_background_geolocation#1113] opened 2023-09-05 16:58 UTC
## Your Environment
* Plugin version: 4.12.2
* Platform: Android
* OS version: API 33
* Device manufacturer / model: Emulator
* Flutter info (`flutter doctor`): [✓] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bgGeo.BackgroundGeolocation.stop();

    bgGeo.Logger.destroyLog();

    bgGeo.BackgroundGeolocation.destroyLocations();

    bgGeo.BackgroundGeolocation.removeListener(_locationHandler);

    bgGeo.BackgroundGeolocation.onLocation(_locationHandler, (error) {
      debugPrint('LocationRepository ERROR - $error');
    });

    await bgGeo.BackgroundGeolocation.ready(bgGeo.Config(
       useSignificantChangesOnly: true, // Apple doesn't want us to use background location services
        desiredAccuracy: bgGeo.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        elasticityMultiplier: 5,
        stopOnTerminate: false,
        startOnBoot: true,
        disableMotionActivityUpdates: true,
        enableHeadless: true,
    )).then((bgGeo.State state) async {

      bgGeo.State afterStartState = await bgGeo.BackgroundGeolocation.start();
      debugPrint(afterStartState.toString());
      if (afterStartState.enabled) {
        debugPrint('LocationRepository bgGeo started');
      } else {
        debugPrint('LocationRepository bgGeo not started');
      }

    });

    bgGeo.BackgroundGeolocation.start();
```

Plugin config
build.gradle
ext {
compileSdkVersion = 33
targetSdkVersion = 33
minSdkVersion = 21
appCompatVersion = "1.4.2"
playServicesVersion = "21.0.1"
}

+--- project :flutter_background_geolocation
| +--- com.transistorsoft:tslocationmanager:+ -> 3.4.4
| +--- org.greenrobot:eventbus:3.3.1
| | --- org.greenrobot:eventbus-java:3.3.1
| +--- com.squareup.okhttp3:okhttp:3.12.13
| | --- com.squareup.okio:okio:1.15.0
| +--- com.github.tony19:logback-android:3.0.0
| +--- org.slf4j:slf4j-api:2.0.7
| +--- io.github.nishkarsh:android-permissions:2.1.6
| | +--- androidx.appcompat:appcompat:1.4.1 -> 1.4.2 ()
| | +--- androidx.localbroadcastmanager:localbroadcastmanager:1.1.0
| | | --- androidx.annotation:annotation:1.1.0 -> 1.6.0 ()
| | --- org.parceler:parceler-api:1.1.12
| +--- com.google.android.gms:play-services-location:20.0.0 -> 21.0.1 (*)

+--- project :geolocator_android
| +--- com.google.android.gms:play-services-location:21.0.1

## Expected Behavior
Should not crash

## Actual Behavior
Crashes

## Steps to Reproduce

1. Once permissions are granted, I call a routine to start the bgGeo service...
2. bgGeo.BackgroundGeolocation.stop() and it crashes

## Context
Initialize and start background location services

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
E/AndroidRuntime(27967): Process: com.maverickgaming.app, PID: 27967
E/AndroidRuntime(27967): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~tTZ_bq8iVPSsywqhWgH9PQ==/com.maverickgaming.app-8MRlwn_pgaKza1PvcPiFfg==/base.apk)
E/AndroidRuntime(27967):        at com.transistorsoft.xms.g.location.FusedLocationProviderClient.removeLocationUpdates(Unknown Source:50)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.location.TSLocationManager.removeLocationUpdates(Unknown Source:40)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.location.TSLocationManager.stopUpdatingLocation(Unknown Source:0)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:0)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:86)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(Unknown Source:2)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.$r8$lambda$oSDeWXxQl1jmikdjYQwff60damw(Unknown Source:0)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(27967):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(27967):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(27967):        at java.lang.Thread.run(Thread.java:1012)
```

</details>

**Comment by christocracy** [comment] 2023-09-05 16:59
I already told you this is a duplicate of #933

**Comment by emaddoma** [comment] 2023-09-05 17:00
And I already told you in the ticket that I've made the changes prescribed.  It still crashes.  Why are you so hostile?

**Closed by christocracy** 2023-09-05 16:59 UTC

**Comment by christocracy** [comment] 2023-09-05 17:03
[java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected](https://www.google.com/search?q=java.lang.IncompatibleClassChangeError%3A+Found+interface+com.google.android.gms.location.FusedLocationProviderClient%2C+but+class+was+expected&oq=java.lang.IncompatibleClassChangeError%3A+Found+interface+com.google.android.gms.location.FusedLocationProviderClient%2C+but+class+was+expected&aqs=chrome..69i57j69i61l3.381j0j7&sourceid=chrome&ie=UTF-8)

**Comment by christocracy** [comment] 2023-09-05 17:06
> playServicesVersion = "21.0.1"

The variable is named __[`playServciesLocationVersion`](https://github.com/transistorsoft/flutter_background_geolocation/blob/599bebdaa08b582f0153b871352188c8278e435d/android/build.gradle#L54C51-L54C78)__

Review the [Android Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidbuildgradle)

**Comment by emaddoma** [comment] 2023-09-05 17:09
Oh jeez.  Thank you.
