### ISSUE TITLE
Regular Android ANRs caused by Transistorsoft Heartbeat and ActivityRecognitionService

### ISSUE THREAD

**Issue by flxwu** [transistorsoft/flutter_background_geolocation#549] opened 2021-04-18 11:33 UTC
## Your Environment
* Plugin version: 2.0.2
* Platform: Android
* OS version: various
* Device manufacturer / model: various
* Flutter info (`flutter doctor`): all green
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
_config = bg.Config(
      heartbeatInterval: 600,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      foregroundService: true,
      activityRecognitionInterval: 5000,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      preventSuspend: true,
      isMoving: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      locationAuthorizationRequest: 'Always',
      enableHeadless: true,
      fastestLocationUpdateInterval: 5000,
      autoSyncThreshold: 5,
      batchSync: true,
      maxBatchSize: 10,
      url: "https://location-console.herokuapp.com/locations",
      params: {...deviceParams, "firebaseUserId": userId},
      autoSync: true,
    );
```

## Expected Behavior
No ANR

## Actual Behavior
Every few hours, we get an ANR modal saying "app is not responding", logcat shows various ANR Reasons related to transistorsoft:

```
04-17 15:11:46.883  4977 25129 E ActivityManager: ANR in com.ovrnite.ovrnite_android
04-17 15:11:46.883  4977 25129 E ActivityManager: PID: 23936
04-17 15:11:46.883  4977 25129 E ActivityManager: Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1dbbc13 u0 com.ovrnite.ovrnite_android/com.transistorsoft.locationmanager.service.ActivityRecognitionService}
04-17 15:11:46.883  4977 25129 E ActivityManager: Load: 20.23 / 19.39 / 19.6
```

```
ANR in com.ovrnite.ovrnite_android
04-17 15:12:35.838  4977 25411 E ActivityManager: PID: 23936
04-17 15:12:35.838  4977 25411 E ActivityManager: Reason: executing service com.ovrnite.ovrnite_android/com.transistorsoft.locationmanager.service.HeartbeatService
```

## Steps to Reproduce
Open App, keep it in background. At some point, ANRs pop up.

## Context

Our OnHeartbeat callback:

```dart
 bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
    bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
    print("[onHeartbeat]: $event");
    });
```

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by flxwu** [comment] 2021-04-18 11:38
Also in the logcat:

```
04-17 15:12:28.435  4977  5022 W ActivityManager: Timeout executing service: ServiceRecord{eeeb8d9 u0 com.ovrnite.ovrnite_android/com.transistorsoft.locationmanager.service.HeartbeatService}
```

**Comment by christocracy** [comment] 2021-04-18 18:58
I've reproduced this.  Fix coming soon as `2.0.3`

**Comment by flxwu** [comment] 2021-04-18 19:26
Awesome, thanks a lot!

**Comment by christocracy** [comment] 2021-04-18 22:27
`2.0.3` is released.

**Comment by flxwu** [comment] 2021-04-19 06:53
Thanks!

**Comment by flxwu** [comment] 2021-04-19 18:07
Hey, we're still getting ANRs on 2.0.3:

```
04-19 18:47:25.410  4977 22139 E ActivityManager: ANR in com.ovrnite.ovrnite_android
04-19 18:47:25.410  4977 22139 E ActivityManager: PID: 20229
04-19 18:47:25.410  4977 22139 E ActivityManager: Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{44fa0c8 u0 com.ovrnite.ovrnite_android/com.transistorsoft.locationmanager.service.HeartbeatService}
```

**Comment by flxwu** [comment] 2021-04-19 18:11
Also, we got the following (not sure if related):

```
04-19 19:15:41.096  4977  5351 W ActivityManager: Foreground service started from background can not have location/camera/microphone access: service com.ovrnite.ovrnite_android/com.transistorsoft.locationmanager.service.HeartbeatService
```

**Comment by christocracy** [comment] 2021-04-19 18:13
The plugin isn't necessarily responsible for your ANR.

It can be your own app code / 3rd Party plugins consuming too much time on the main thread, preventing the plugin's services from calling startForeground in time.

Boot your app with strictMode enabled to learn which components are consuming too much time in main-thread.

https://developer.android.com/reference/android/os/StrictMode

**Comment by flxwu** [comment] 2021-04-19 18:22
Is the following related?
```
ActivityManager: Foreground service started from background can not have location/camera/microphone access: service com.ovrnite.ovrnite_android/com.transistorsoft.locationmanager.service.HeartbeatService
```

And, can you surely rule out that the plugin isn't responsible for the ANRs? FWIW, we didn't get any ANRs in the v1.9.0 lib.

**Comment by christocracy** [comment] 2021-04-19 18:28
It's a very well known issue with Android apps.

Google it:

https://www.google.com/search?q=context.startForegroundService&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari

You **must** boot your app with StrictMode to learn more.  Do it now.

**Comment by flxwu** [comment] 2021-04-19 18:31
Just doing now, and we're getting a bunch of:

```
2021-04-19 20:25:03.163 29127-29127/com.ovrnite.ovrnite_android D/StrictMode: StrictMode policy violation; ~duration=56 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7537)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:681)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:672)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:628)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:853)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:475)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
        at com.transistorsoft.locationmanager.location.TSLocationManager.clearLastOdometerLocation(Unknown Source:33)
        at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:3)
        at com.transistorsoft.locationmanager.service.TrackingService.e(Unknown Source:72)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.stop(Unknown Source:35)
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.stop(BackgroundGeolocationModule.java:430)
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.onMethodCall(BackgroundGeolocationModule.java:228)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by christocracy** [comment] 2021-04-19 18:34
It's not unusual to see policy violations.

> 56 ms

I'm not worried about 56ms

**Comment by christocracy** [comment] 2021-04-19 18:36
The policy violations you're concerned about are those where your app *launches*.

**Comment by flxwu** [comment] 2021-04-19 18:38
We don't have any other policy violations, except one coming from BackgroundLocationModule.applyConfig.

**Comment by zirkler** [comment] 2021-04-19 18:44
Dear @christocracy, I'm experiencing the same issue since I updated to 2.x.x.

**Comment by christocracy** [comment] 2021-04-19 18:45
Install latest releases yesterday.

**Comment by zirkler** [comment] 2021-04-19 18:45
That's what I did, with 1.x.x I was not seeing any ANRs.

**Comment by christocracy** [comment] 2021-04-19 18:49
I don't know.

**Comment by christocracy** [comment] 2021-04-19 18:51
There is little difference between 1.x vs 2.x with Android.

The bump to 2.x was merely for change in build structure of iOS TSLocationManager.xcframework.

**Comment by flxwu** [comment] 2021-04-19 19:09
Would you mind looking into this, and seeing if you can reproduce it? On some devices, it pops up after running the app in the background for a few hours, on others after a few minutes already.

**Comment by christocracy** [comment] 2021-04-19 19:11
- I have released the latest example app to play store today.
- I am monitoring issues with the Cordova/ReactNative versions as well.
- I am field-testing with 13 Android devices.

**Comment by christocracy** [comment] 2021-04-19 20:26
>using the latest version

What specific version?

>flutter doctor

**Comment by ivanfjr1** [comment] 2021-04-19 20:27
version 2.0.3, released yesterday

**Comment by christocracy** [comment] 2021-04-19 20:27
>flutter doctor

**Comment by ivanfjr1** [comment] 2021-04-19 20:28
`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [versÃ£o 10.0.19042.928], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)
`

**Comment by christocracy** [comment] 2021-04-19 20:28
Try on a real device.

**Comment by ivanfjr1** [comment] 2021-04-19 20:30
On a oneplus 5 happening the same thing but less often

**Comment by ivanfjr1** [comment] 2021-04-19 20:32
![image](https://user-images.githubusercontent.com/9275996/115299512-44877a00-a135-11eb-9a45-f12ad65e3957.png)

**Comment by ivanfjr1** [comment] 2021-04-19 20:36
Iif you need more information, I am available

**Comment by christocracy** [comment] 2021-04-19 20:38
I have nothing to add.  I am testing 3 different versions of the /example app for *Cordova*, *React Native* and *Flutter* on the following 13 devices.  I cannot reproduce the problem:
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 11
- Samsung Galaxy S20 FE @ 11.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by ivanfjr1** [comment] 2021-04-19 20:39
When i open google maps, it seems that it happens easier

**Comment by zirkler** [comment] 2021-04-19 20:40
@christocracy would you mind giving a little more info on how you run your tests? Are the devices receiving any location events? Are you running a location mock app during those tests?

**Comment by christocracy** [comment] 2021-04-19 20:43
I am testing with the `/example` app in this repo.  I am testing with 
- real field-testing.
- rapidly terminating / restarting the *Cordova*, *React Native* and *Flutter* example apps.

**Comment by christocracy** [comment] 2021-04-19 20:48
or install from Play Store https://play.google.com/store/apps/details?id=com.transistorsoft.flutterbackgroundgeolocationexample

**Comment by christocracy** [comment] 2021-04-19 21:45
I was able to get an ANR on my *Huawei P20 Lite* while rapidly open/closing my example apps.

I have a hunch about something.  Try installing from Git branch `release-2.0.4` and attempt to reproduce:

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: release-2.0.4
```

**Comment by ivanfjr1** [comment] 2021-04-19 22:47
I'm doing tests with this release-2.0.4 version, and I couldn't simulate it anymore, I'm still following it on the emulator and on the oneplus 5 device, thank you very much for the quick return.

**Comment by christocracy** [comment] 2021-04-19 23:26
> and I couldn't simulate it anymore

You mean you couldn't *reproduce* it anymore?

**Comment by ivanfjr1** [comment] 2021-04-19 23:31
That's right, I couldn't simulate the error anymore

**Comment by christocracy** [comment] 2021-04-27 15:36
`2.0.5` has been running live in the /`example` app on Play Store since *April 21* with no reported crash or ANR after *233 installs*.

**Comment by christocracy** [comment] 2021-04-27 21:13
*Cordova* and *React Native* users also report ANR have disappeared with latest version.

**Closed by christocracy** 2021-04-27 21:13 UTC
